- import_playbook: in-memory-inventory.yml

- name: Ping Test
  hosts: all
  tasks:
    - name: Task - Ping
      ping:

- name: End to end smoke tests
  hosts: app_servers:database_servers
  gather_facts: true
  become: true
  tags:
    - smoketest  

  tasks:

    - name: Smoketest Postgres database
      postgresql_ping:
        db: flask_db
        login_host: "{{ groups.database_servers[0] }}"
        login_user: flask
        login_password: redhat
        ssl_mode: disable
      delegate_to: "{{ groups.app_servers[0] }}"
      run_once: true
      tags:
        - smoketest

- name: End to end smoke tests
  hosts: app_servers
  become: false
  gather_facts: false
  tags:
    - smoketest  
  tasks:
 
    - name: Check webserver for correct response (IP)
      uri:
        url: "http://192.168.51.18/ping"
        return_content: yes
      until: '"alive" in result.content'
      retries: 5
      delay: 1
      register: result
      delegate_to: localhost
